# Generated by Django 5.0.7 on 2024-08-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unit',
            field=models.CharField(max_length=100),
        ),
    ]
