# Generated by Django 5.0.7 on 2024-08-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('english_name', models.CharField(max_length=100)),
                ('arabic_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
