# Generated by Django 5.0.7 on 2024-08-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_projectphase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectphase',
            name='arabic_name',
        ),
        migrations.RemoveField(
            model_name='projectphase',
            name='description',
        ),
    ]
