# Generated by Django 5.0.7 on 2024-08-19 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_remove_projectphase_arabic_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectphase',
            old_name='english_name',
            new_name='phase_name',
        ),
    ]
