# Generated by Django 5.0.7 on 2024-08-19 06:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_alter_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=20)),
                ('project_name', models.CharField(max_length=255)),
                ('project_code', models.CharField(max_length=100)),
                ('project_phase', models.CharField(max_length=100)),
                ('project_consultant', models.CharField(max_length=255)),
                ('project_location', models.CharField(max_length=255)),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('supply_date', models.DateField()),
                ('products', models.ManyToManyField(related_name='product_orders', to='products.product')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='orders.order')),
            ],
        ),
    ]
